### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alitehami** [EverseDevelopment/revit-glTF-exporter#68]
Hello,

Thanks for your open-source contribution with this project to the AEC industry. Great work!

I couldn't find your license on the public GitHub page, what license are you open-sourcing this with?

Thanks!
Ali T.

**Comment by vnoves** [comment]
Hi @alitehami, thanks for checking our repo, and we are glad you liked it.
I just added an MIT license to this repo. If you will use it for another project, please let us know. We would love to see how other people are using our code :).

Also, feel free to collaborate too!

Best,

**Comment by alitehami** [comment]
Awesome, thank you @vnoves
